<a href="https://colab.research.google.com/github/GGGoradia/Machine-learning-lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [3]:
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [4]:
arr2=np.arange(1,10,2)
print(arr2)

[1 3 5 7 9]
