<a href="https://colab.research.google.com/github/GGGoradia/Machine-learning-lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [ ]:
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr2=np.arange(1,10,2)
print(arr2)

[1 3 5 7 9]


In [40]:
#1
arr2d=np.array([[18,21,3,6],[5,1,0,11],[0,7,0,33]])
print(arr2d)

[[18 21  3  6]
 [ 5  1  0 11]
 [ 0  7  0 33]]


In [41]:
#1a
index=np.where(arr2d==0)
print(index)

(array([1, 2, 2]), array([2, 0, 2]))


In [44]:
#1b
tra=arr2d.transpose()
print(tra)
print("")
print(arr2d[1])

[[18  5  0]
 [21  1  7]
 [ 3  0  0]
 [ 6 11 33]]

[ 5  1  0 11]


In [46]:
#1c
flat=arr2d.flatten()
print(flat)

[18 21  3  6  5  1  0 11  0  7  0 33]


In [49]:
np.savetxt("mat.txt",arr2d)

In [53]:
#2
arr2=np.loadtxt("Mark.txt",skiprows=1)
print(arr2)

[[60. 66. 70.]
 [99. 78. 88.]
 [55. 61. 54.]
 [84. 81. 73.]
 [55. 54. 53.]
 [77. 72. 79.]
 [80. 80. 80.]
 [90. 95. 93.]]
