<a href="https://colab.research.google.com/github/GGGoradia/Machine-learning-lab/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
import pandas as pd
df=pd.read_csv('Customer_buy.csv')
inputs=np.hstack((df.iloc[:,:-1],np.ones((len(df),1))))
outputs=df.iloc[:,-1]
print(input)
print(outputs)
w=np.zeros(3)

[[ 2. 10.  1.]
 [ 3. 25.  1.]
 [ 5. 10.  1.]
 [ 5. 30.  1.]
 [ 4. 15.  1.]
 [ 6. 25.  1.]]
0    0
1    1
2    0
3    1
4    0
5    1
Name: Class, dtype: int64


In [48]:
def sigmoid(x):
  return 1/(1+np.exp(-1*x))

In [49]:
def infer(w,x):
  return sigmoid(np.dot(w,x))
def epoch(w,inputs,outputs):
  s=np.zeros(3)
  for i in range (0,len(inputs)):
    s+=(infer(w,inputs[i])-outputs[i])*inputs[i]
  return s

In [52]:
for _ in range (0,2):
  w-=0.1*epoch(w,inputs,outputs)/len(inputs)
w

array([-0.11535733,  0.51661649, -0.052134  ])

In [53]:
infer(w,np.array([5,30,1]))

0.999999651481495